config/routes.rb
Kicktempo::Application.routes.draw do
  captcha_route
  mount Ckeditor::Engine => '/ckeditor'
  
  mount ChinaCity::Engine => '/china_city'

  match 'newhome/:action' => 'newhome', via: [:get,:post]
  match 'my/:action' => 'my', via: [:get,:post]

  resources :game_albums do
    collection do
      get 'face'
      get 'show/:user_id' => 'game_albums#show'
      put 'upload_face'
    end
  end
  resources :leagues do

    collection do
      post :search_friends
      post :invite
      get  :invite_check
      get  :check_name
      post :update_league
      get  'ignore/:id'=> 'leagues#ignore',as: :ignore
      get  'accept/:id'=> 'leagues#accept',as: :accept
      post :accept
    end
  end
  get  'my_leagues'=>'leagues#my_leagues', as: :my_leagues
  #get 'game_albums/face'

  get "autodata/index"

  get  '/games' => 'games#index'
  get  '/games/list' => 'games#list'
  post '/games/registration' => 'games#registration'
  get  '/games/terms' => 'games#game_terms', as: :game_terms
  get  '/games/rank' => 'games#rank'
  get  '/games/scores_list'=> 'games#scores_list'
  get  '/games/league_scores_list'=> 'games#league_scores_list'
  get  '/games/next_vedio' => 'games#slide'
  get  '/games/one_next_vedio' => 'games#one_slide'
  get  '/games/check_score'
  put  '/games/score'
  get  '/bags/search' => 'bags#search'

  get  '/games/show' => 'games#show'
  post  '/games/join' => 'games#join'
  post  '/games/invite' => 'games#invite'


  match '/activities/:year/:month/:day/:url/' => 'games#scene', :constraints => { :url => /.+/ }, via: [:get,:post]

  get  '/new_plant' => 'new_plant#index'
  get  '/about_us' => 'new_plant#about_us'
  get  '/support_our_plant' => 'new_plant#support_our_plant'
  get  '/kicktempo_story' => 'new_plant#kicktempo_story'
  get  '/school_list' => 'new_plant#school_list'
  get  '/donate' => 'new_plant#donate'
  get  '/donated_citys' => 'new_plant#donated_citys'
  get  '/donated_schools' => 'new_plant#donated_schools'
  get  '/plant_news' => 'new_plant#plant_news'
  get  'support_kicktempo' => 'new_plant#support_kicktempo'
  get  'gas_intro' => 'new_plant#gas_intro'
  get  'company' => 'new_plant#company'
  post 'send_message' => 'new_plant#send_message'
  post 'send_donate_message' => 'new_plant#create_donate_message'

  get  '/confirm_phone' => 'users#confirm_phone', as: :confirm_phone
  get  '/invite' => 'users#invite', as: :invite
  get  '/connect_auths' => 'users#connect_auths', as: :connect_auths
  get  '/subscribe_sms' => 'users#subscribe_sms', as: :subscribe_sms
  get  '/myorders' => 'users#myorders', as: :myorders
  get  '/myclubbers/:type/:manager' => 'users#myclubbers', as: :myclubbers
  post '/varify_phone' => 'users#varify_phone', as: :varify_phone
  post '/varify_subscribe_sms' => 'users#varify_subscribe_sms', as: :varify_subscribe_sms
  get  '/send_varification_code' => 'users#send_code', as: :send_code
  post '/varify_code' => 'users#varify_code', as: :varify_code
  get  '/my_space' => 'users#myspace', as: :myspace
  get  '/user/:user_id' => 'users#home', as: :user_home
  get  '/shows/my' => 'game_vedios#my_shows', as: :my_shows
  get  '/shows/:id' => 'game_vedios#show'
  get  '/my_scores' => 'users#my_scores'
  #get  '/user/:user_id/game_vedios' => 'game_vedios#index', as: :user_game_vedios

  match '/users/auth/Youku/callback(.:format)' => 'admin/admission#set_youku', via: [:get,:post]

  devise_for :users, controllers: {
    sessions:           :sessions,
    omniauth_callbacks: :authentications,
    registrations: :registrations
  }

  devise_scope :user do
    #get '/sign_up' => "registrations#new", as: :sign_up
    get '/sign_in' => "devise/sessions#new", as: :sign_in
    get '/sign_out' => "devise/sessions#destroy", as: :sign_out
    post  '/sign_up'  => 'registrations#create'
    post '/get_authcode' => 'registrations#get_authcode'
    put '/authuser_update' => 'registrations#authuser_update', as: :authuser_update
  end

  # weixin
  get '/wx_callback' => "weixin/weixin_api#callback_get"
  post '/wx_callback' => "weixin/weixin_api#callback_post"
  get '/weixin/train' => "weixin/pages#train"

  resources :clubs

  namespace :api do
    resources :users, only: [] do
      get 'vedios', on: :member
      collection do
        get 'user_info'
        post 'login'
        post 'sign_up'
        get 'base_info'
        post 'update_profile'
        post 'auth_connect'
        post 'share'
        get 'auth_info'
        get 'auth_redirect_uri'
        post 'oauth_login'
        post 'oauth_signup'
      end
    end

    resources :games, only: [:index, :show] do
      collection do
        post 'post_score'
        get 'citys'
        get 'countrys'
        get 'country_cities'
        get 'rank'
        get 'page_rank'
        get 'page_league_rank'
        post 'create_game'
        post 'post_league'
        get 'city_games'
        post 'bag_trace'
        post 'post_face'
      end
    end

    resources :admin, only: [] do
      get 'youku_token', on: :collection
      get 'refresh_youkutoken', on: :collection
    end

    resources :articles, only: [:index, :show] do
      get 'game_intro', on: :collection
      get 'game_terms', on: :collection
    end

    resources :game_vedios, only: [:index, :show] do
      post 'post_vedio', on: :collection
    end
  end

  namespace :weixin do
    get 'w_services/get_gz_reply_content' => 'w_services#get_gz_reply_content'
    get 'w_services/get_auto_reply_content' => 'w_services#get_auto_reply_content'

    resources :w_services do
      member do
        get 'first_gz'
        get 'auto_reply'
      end
    end

    match 'w_replies/get_reply_content' => 'w_replies#get_reply_content', via: [:get]
    resources :w_replies

    resources :w_users do
      get 'unbind', on: :member
    end
    resources :materials do
      get 'preview', on: :member
    end
    resources :multiple_materials do
      get 'edit_list', on: :member
      post 'update_list', on: :member
      get 'preview', on: :member
    end
    resources :multiple_material_lists do
      get 'preview', on: :member
    end
    resources :audio_materials
    resources :w_questions
    resources :w_question_answers

    resources :w_menus do
      get 'sync', on: :collection
    end
    resources :w_cities
    resources :w_media
    resources :w_brands

    match 'users/:action' => 'users', via: [:get,:post]
    match 'pages/:action' => 'pages', via: [:get,:post]

  end
  get '/weixin/w_users/:id/unbind' => 'weixin/w_users#unbind'
  get '/time' => 'home#time'
  
  namespace :newadmin do
    resources :games do
      get 'view_applications', on: :member
    end
    resources :kt_errors do
      get 'solve', on: :member
    end
    resources :online_courses
    resources :students
    resources :coaches

    resources :donate_messages
    resources :school_items
    resources :companies
    resources :albums do
      get 'upload', on: :member
      post 'upload', on: :member
    end
    resources :articles
  end

  namespace :admin do
    get  '/index' => 'home#index'
    resources :games
    resources :gifts
    resources :orders
    resources :rounds
    resources :messages
    resources :donate_messages
    resources :companies
    resources :school_locals
    resources :school_items
    resources :countries
    resources :clubs
    resources :bags
    resources "bag_traces"
    resources :albums do
      resources :pictures, only: [] do
        get 'multi_edit', as: :multi_edit, on: :collection
        post 'multi_update', as: :multi_update, on: :collection
      end
    end
    resources :pictures do
      collection do
        get 'uploads', as: :uploads
      end
    end

    post '/games/open'
    post '/games/close'
    post '/games/start'
    post '/games/finish'

    get  '/users' => 'users#index'
    get  '/users/search' => 'users#search'
    get  '/users/profile' => 'users#profile'
    get  '/users/subscribed_sms'  => 'users#subscribed_sms'
    get  '/users/unsubscribed_sms'  => 'users#unsubscribed_sms'
    post  '/users/cancel_subscribed_sms'  => 'users#cancel_subscribed_sms'
    post  '/users/confirm_subscribed_sms'  => 'users#confirm_subscribed_sms'
    get  '/users/agent_list' => 'users#agent_list'
    get  '/users/judge_list' => 'users#judge_list'

    post  '/users/check_sms'  => 'users#check_sms'
    post  '/users/uncheck_sms'  => 'users#uncheck_sms'
    post  '/users/selected_sms'  => 'users#selected_sms'
    post  '/users/cancel_selected_sms'  => 'users#cancel_selected_sms'


    post '/users/admin' => 'users#admin'
    get '/users/setjudge' => 'users#setjudge'
    put '/users/judge' => 'users#judge'
    get '/users/setagent' => 'users#setagent'
    put '/users/agent' => 'users#agent'
    get  '/users/new' => 'users#new'
    get  '/users/tally' => 'users#tally'
    get  '/users/day_top_scores' => 'users#day_top_scores'
    get  '/users/day_rounds' => 'users#day_rounds'
    get  '/users/day_goals' => 'users#day_goals'
    get  '/users/day_games' => 'users#day_games'
    post '/users' => 'users#create'
    post '/users/registration' => 'users#registration'
    post '/users/admission' => 'users#admission'
    post '/users/phone' => 'users#phone'
    post '/users/area' => 'users#area'
    post '/users/destroy' => 'users#destroy'
    post '/users/batch_signup' => 'users#batch_signup'
    get '/users/batch_index' => 'users#batch_index'
    get '/users/setvip' => 'users#setvip'
    put '/users/updatevip' => 'users#updatevip'
    get '/users/cancelvip' => 'users#cancelvip'

    get  '/admission' => 'admission#index'
    post '/admission/admit' => 'admission#admit'
    get  '/admission/entered' => 'admission#entered'

    get  '/scores' => 'scores#index'
    post '/scores/submit' => 'scores#submit'
    get  '/scores/list' => 'scores#list'

    get '/levels' => 'levels#index'
    get '/levels/rules' => 'levels#rules'


    get '/articles/:id/set_visit' => 'articles#set_visit'

    resources :articles
    resources :new_plants

    resources :info_urls

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user, class_name: "User"
end

app/controllers/admin/orders_controller.rb
# -*- coding: utf-8 -*-
class Admin::OrdersController < AdminController
  inherit_resources
  respond_to :html, :json
  
  def index
    @orders = Order.order("created_at desc").page(params[:page]).per(15)
  end
  
end

app/controllers/orders_controller.rb
# -*- coding: utf-8 -*-
class OrdersController < ApplicationController
  before_filter :must_logged_in
  
  def check_identity
    u= User.find(current_user.id)
    result = u.is_judge==true ? 1 : 0
    render :text => result
  end
  
  def check_scores
    result=0
    gift = Gift.find(params[:id])
     
    result=1                  if current_user.coins >= gift.scores
    result=current_user.coins if current_user.coins < gift.scores
    
    render :text => result
  end
  
  def address
    @order=Order.new
    @gift= Gift.find(params[:id])
  end
  
  def show
    @order = Order.find(params[:id])
    if current_user.id != @order.user_id
      redirect_to root_path, notice: '不可以查看不属于你的订单'
    end
  end
  
  def exchange
    gift=Gift.find(params[:order][:gift_id])
    #judge_rank = JudgeRank.find_by_user_id(current_user.id)
    puts "--exchange--#{current_user.id}-before-scores:#{current_user.coins}---兑换礼品积分:#{gift.scores}--#{Time.new}"
    order = Order.new(params[:order])
    order.user_id = current_user.id
    order.gift_name = gift.name
    order.scores = gift.scores
    order.status=1
    current_user.coins -= gift.scores
    if current_user.save && order.save
      redirect_to "/orders/#{order.id}/show"
    else
      puts "exchange--#{current_user.id}--#{params[:order][:gift_id]}---"
      redirect_to "/address/#{gift.id}",notice: '兑换出错，请重新兑换'
    end
  end
  
end

app/views/admin/orders/_exorder.html.slim
= javascript_include_tag 'ckeditor/init'
= form_for [:admin, @order] do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message
  
  

  .field
    = f.label "购买产品:"
    br
    = f.text_field :gift_name,:value=>nil
  .field
    = f.label "KT USER ID:",:value=>nil
    br
    = f.text_field :user_id
    = f.hidden_field :source_type,:value =>1
  .field
    = f.label "支付宝:"
    br
    = f.text_field :receive_by
  .field
    = f.label "手机:"
    br
    = f.text_field :phone  
  .field
    = f.label "充值金额:"
    br
    = f.text_field :scores
  
  
  
  .actions = f.submit '保存'

app/views/admin/orders/_form.html.slim
= javascript_include_tag 'ckeditor/init'
= form_for [:admin, @order] do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message  
 

  .field
    = f.label "礼品名称:"
    = @order.gift_name
  .field
    = f.label @order.source_type==0?"积分:":"充值金额："
    = f.text_field :scores
  .field
    = f.label "收货人:"
    br
    = f.text_field :receive_by
  .field
    = f.label "手机:"
    br
    = f.text_field :phone
  - if 0 == @order.source_type
      .field
        = f.label "兑换人:"
        = @order.user.nickname     
      .field
        = f.label "订单状态:"
        = f.select(:status, options_for_select((1..4).to_a, @order.status) ) 
        |  1:兑换成功；2:已配送；3:已签收；4:失败
      .field
        = f.label '送货地址:'
        br
        = f.text_field :address
      .field
        = f.label '发货日期:'
        br
        = f.text_field :send_day
  
  .actions = f.submit '保存'

app/views/admin/orders/edit.html.slim
h1 编辑订单
= link_to '显示', [:admin, @order]
||
= link_to '后退', admin_orders_path

== render 'form'

app/views/admin/orders/index.html.slim
span
  = link_to '新建淘宝订单', new_admin_order_path

table
  tr
    th ID
    th 订单
    th 兑换人
    th 兑换礼品
    th 积分
    th 状态
    th 收货人
    th 手机
    th 送货地址
    th 送货日期
    th 购买时间
    th
    th
    th

  - @orders.each do |o|
    tr
      td = text_field_tag(:id,o.id, :disabled => true,:size => 3)
      td = o.source_type==0?"兑换":"淘宝"
      td = text_field_tag(:user_id,o.user.nickname, :disabled => true,:size => 3) if o.user.present?
      td = text_field_tag(:gift_name,o.gift_name, :disabled => true,:size => 15)
      td = text_field_tag(:scores,o.scores, :disabled => true,:size => 7)
      td = text_field_tag(:status,o.status, :disabled => true,:size => 5)
      td = text_field_tag(:receive_by,o.receive_by, :disabled => true,:size => 12)
      td = text_field_tag(:phone,o.phone, :disabled => true,:size => 12)
      td = text_field_tag(:address,o.address, :disabled => true,:size => 12)
      td = text_field_tag(:send_day,o.send_day, :disabled => true,:size => 12)
      td = text_field_tag(:created_at,o.created_at, :disabled => true,:size => 20)
      td = link_to '显示', [:admin, o]
      td = link_to '编辑', edit_admin_order_path(o)
      td = link_to '删除', [:admin, o], confirm: '你确定么？', method: :delete
= paginate @orders

app/views/admin/orders/new.html.slim
h1 新建
= link_to '后退', admin_orders_path

== render 'exorder'

app/views/admin/orders/show.html.slim
p#notice = notice
= link_to '编辑', edit_admin_order_path(@order)
||
= link_to '后退', admin_orders_path
p
  string 兑换人:
  = @order.user.nickname if @order.user.present?
p
  strong 礼品名称：
  = @order.gift_name
p
  strong #{@order.source_type==0?"积分：":"充值金额："}
  = @order.scores

p
  strong 收货人：
  = @order.receive_by
p
  strong 收货手机：
  = @order.phone
- if 0 == @order.source_type
    p
      strong 状态：
      = @order.status
      |     状态说明:[1:兑换成功；2:已配送；3:已签收；4:失败］
    p
      strong 收货地址：
      = @order.address

.clear