config/routes.rb
Kicktempo::Application.routes.draw do
  captcha_route
  mount Ckeditor::Engine => '/ckeditor'
  
  mount ChinaCity::Engine => '/china_city'

  match 'newhome/:action' => 'newhome', via: [:get,:post]
  match 'my/:action' => 'my', via: [:get,:post]

  resources :game_albums do
    collection do
      get 'face'
      get 'show/:user_id' => 'game_albums#show'
      put 'upload_face'
    end
  end
  resources :leagues do

    collection do
      post :search_friends
      post :invite
      get  :invite_check
      get  :check_name
      post :update_league
      get  'ignore/:id'=> 'leagues#ignore',as: :ignore
      get  'accept/:id'=> 'leagues#accept',as: :accept
      post :accept
    end
  end
  get  'my_leagues'=>'leagues#my_leagues', as: :my_leagues
  #get 'game_albums/face'

  get "autodata/index"

  get  '/games' => 'games#index'
  get  '/games/list' => 'games#list'
  post '/games/registration' => 'games#registration'
  get  '/games/terms' => 'games#game_terms', as: :game_terms
  get  '/games/rank' => 'games#rank'
  get  '/games/scores_list'=> 'games#scores_list'
  get  '/games/league_scores_list'=> 'games#league_scores_list'
  get  '/games/next_vedio' => 'games#slide'
  get  '/games/one_next_vedio' => 'games#one_slide'
  get  '/games/check_score'
  put  '/games/score'
  get  '/bags/search' => 'bags#search'

  get  '/games/show' => 'games#show'
  post  '/games/join' => 'games#join'
  post  '/games/invite' => 'games#invite'


  match '/activities/:year/:month/:day/:url/' => 'games#scene', :constraints => { :url => /.+/ }, via: [:get,:post]

  get  '/new_plant' => 'new_plant#index'
  get  '/about_us' => 'new_plant#about_us'
  get  '/support_our_plant' => 'new_plant#support_our_plant'
  get  '/kicktempo_story' => 'new_plant#kicktempo_story'
  get  '/school_list' => 'new_plant#school_list'
  get  '/donate' => 'new_plant#donate'
  get  '/donated_citys' => 'new_plant#donated_citys'
  get  '/donated_schools' => 'new_plant#donated_schools'
  get  '/plant_news' => 'new_plant#plant_news'
  get  'support_kicktempo' => 'new_plant#support_kicktempo'
  get  'gas_intro' => 'new_plant#gas_intro'
  get  'company' => 'new_plant#company'
  post 'send_message' => 'new_plant#send_message'
  post 'send_donate_message' => 'new_plant#create_donate_message'

  get  '/confirm_phone' => 'users#confirm_phone', as: :confirm_phone
  get  '/invite' => 'users#invite', as: :invite
  get  '/connect_auths' => 'users#connect_auths', as: :connect_auths
  get  '/subscribe_sms' => 'users#subscribe_sms', as: :subscribe_sms
  get  '/myorders' => 'users#myorders', as: :myorders
  get  '/myclubbers/:type/:manager' => 'users#myclubbers', as: :myclubbers
  post '/varify_phone' => 'users#varify_phone', as: :varify_phone
  post '/varify_subscribe_sms' => 'users#varify_subscribe_sms', as: :varify_subscribe_sms
  get  '/send_varification_code' => 'users#send_code', as: :send_code
  post '/varify_code' => 'users#varify_code', as: :varify_code
  get  '/my_space' => 'users#myspace', as: :myspace
  get  '/user/:user_id' => 'users#home', as: :user_home
  get  '/shows/my' => 'game_vedios#my_shows', as: :my_shows
  get  '/shows/:id' => 'game_vedios#show'
  get  '/my_scores' => 'users#my_scores'
  #get  '/user/:user_id/game_vedios' => 'game_vedios#index', as: :user_game_vedios

  match '/users/auth/Youku/callback(.:format)' => 'admin/admission#set_youku', via: [:get,:post]

  devise_for :users, controllers: {
    sessions:           :sessions,
    omniauth_callbacks: :authentications,
    registrations: :registrations
  }

  devise_scope :user do
    #get '/sign_up' => "registrations#new", as: :sign_up
    get '/sign_in' => "devise/sessions#new", as: :sign_in
    get '/sign_out' => "devise/sessions#destroy", as: :sign_out
    post  '/sign_up'  => 'registrations#create'
    post '/get_authcode' => 'registrations#get_authcode'
    put '/authuser_update' => 'registrations#authuser_update', as: :authuser_update
  end

  # weixin
  get '/wx_callback' => "weixin/weixin_api#callback_get"
  post '/wx_callback' => "weixin/weixin_api#callback_post"
  get '/weixin/train' => "weixin/pages#train"

  resources :clubs

  namespace :api do
    resources :users, only: [] do
      get 'vedios', on: :member
      collection do
        get 'user_info'
        post 'login'
        post 'sign_up'
        get 'base_info'
        post 'update_profile'
        post 'auth_connect'
        post 'share'
        get 'auth_info'
        get 'auth_redirect_uri'
        post 'oauth_login'
        post 'oauth_signup'
      end
    end

    resources :games, only: [:index, :show] do
      collection do
        post 'post_score'
        get 'citys'
        get 'countrys'
        get 'country_cities'
        get 'rank'
        get 'page_rank'
        get 'page_league_rank'
        post 'create_game'
        post 'post_league'
        get 'city_games'
        post 'bag_trace'
        post 'post_face'
      end
    end

    resources :admin, only: [] do
      get 'youku_token', on: :collection
      get 'refresh_youkutoken', on: :collection
    end

    resources :articles, only: [:index, :show] do
      get 'game_intro', on: :collection
      get 'game_terms', on: :collection
    end

    resources :game_vedios, only: [:index, :show] do
      post 'post_vedio', on: :collection
    end
  end

  namespace :weixin do
    get 'w_services/get_gz_reply_content' => 'w_services#get_gz_reply_content'
    get 'w_services/get_auto_reply_content' => 'w_services#get_auto_reply_content'

    resources :w_services do
      member do
        get 'first_gz'
        get 'auto_reply'
      end
    end

    match 'w_replies/get_reply_content' => 'w_replies#get_reply_content', via: [:get]
    resources :w_replies

    resources :w_users do
      get 'unbind', on: :member
    end
    resources :materials do
      get 'preview', on: :member
    end
    resources :multiple_materials do
      get 'edit_list', on: :member
      post 'update_list', on: :member
      get 'preview', on: :member
    end
    resources :multiple_material_lists do
      get 'preview', on: :member
    end
    resources :audio_materials
    resources :w_questions
    resources :w_question_answers

    resources :w_menus do
      get 'sync', on: :collection
    end
    resources :w_cities
    resources :w_media
    resources :w_brands

    match 'users/:action' => 'users', via: [:get,:post]
    match 'pages/:action' => 'pages', via: [:get,:post]

  end
  get '/weixin/w_users/:id/unbind' => 'weixin/w_users#unbind'
  get '/time' => 'home#time'
  
  namespace :newadmin do
    resources :games do
      get 'view_applications', on: :member
    end
    resources :kt_errors do
      get 'solve', on: :member
    end
    resources :online_courses
    resources :students
    resources :coaches

    resources :donate_messages
    resources :school_items
    resources :companies
    resources :albums do
      get 'upload', on: :member
      post 'upload', on: :member
    end
    resources :articles
  end

  namespace :admin do
    get  '/index' => 'home#index'
    resources :games
    resources :gifts
    resources :orders
    resources :rounds
    resources :messages
    resources :donate_messages
    resources :companies
    resources :school_locals
    resources :school_items
    resources :countries
    resources :clubs
    resources :bags
    resources "bag_traces"
    resources :albums do
      resources :pictures, only: [] do
        get 'multi_edit', as: :multi_edit, on: :collection
        post 'multi_update', as: :multi_update, on: :collection
      end
    end
    resources :pictures do
      collection do
        get 'uploads', as: :uploads
      end
    end

    post '/games/open'
    post '/games/close'
    post '/games/start'
    post '/games/finish'

    get  '/users' => 'users#index'
    get  '/users/search' => 'users#search'
    get  '/users/profile' => 'users#profile'
    get  '/users/subscribed_sms'  => 'users#subscribed_sms'
    get  '/users/unsubscribed_sms'  => 'users#unsubscribed_sms'
    post  '/users/cancel_subscribed_sms'  => 'users#cancel_subscribed_sms'
    post  '/users/confirm_subscribed_sms'  => 'users#confirm_subscribed_sms'
    get  '/users/agent_list' => 'users#agent_list'
    get  '/users/judge_list' => 'users#judge_list'

    post  '/users/check_sms'  => 'users#check_sms'
    post  '/users/uncheck_sms'  => 'users#uncheck_sms'
    post  '/users/selected_sms'  => 'users#selected_sms'
    post  '/users/cancel_selected_sms'  => 'users#cancel_selected_sms'


    post '/users/admin' => 'users#admin'
    get '/users/setjudge' => 'users#setjudge'
    put '/users/judge' => 'users#judge'
    get '/users/setagent' => 'users#setagent'
    put '/users/agent' => 'users#agent'
    get  '/users/new' => 'users#new'
    get  '/users/tally' => 'users#tally'
    get  '/users/day_top_scores' => 'users#day_top_scores'
    get  '/users/day_rounds' => 'users#day_rounds'
    get  '/users/day_goals' => 'users#day_goals'
    get  '/users/day_games' => 'users#day_games'
    post '/users' => 'users#create'
    post '/users/registration' => 'users#registration'
    post '/users/admission' => 'users#admission'
    post '/users/phone' => 'users#phone'
    post '/users/area' => 'users#area'
    post '/users/destroy' => 'users#destroy'
    post '/users/batch_signup' => 'users#batch_signup'
    get '/users/batch_index' => 'users#batch_index'
    get '/users/setvip' => 'users#setvip'
    put '/users/updatevip' => 'users#updatevip'
    get '/users/cancelvip' => 'users#cancelvip'

    get  '/admission' => 'admission#index'
    post '/admission/admit' => 'admission#admit'
    get  '/admission/entered' => 'admission#entered'

    get  '/scores' => 'scores#index'
    post '/scores/submit' => 'scores#submit'
    get  '/scores/list' => 'scores#list'

    get '/levels' => 'levels#index'
    get '/levels/rules' => 'levels#rules'


    get '/articles/:id/set_visit' => 'articles#set_visit'

    resources :articles
    resources :new_plants

    resources :info_urls

app/controllers/admin/games_controller.rb
# -*- coding: utf-8 -*-
class Admin::GamesController < AdminController
  inherit_resources
  respond_to :html, :json

   def index
    hash = {}
    hash[:city] = params[:city] unless params[:city].blank?
    @games = Game.where(hash).order('updated_at desc').page(params[:page]).per(20)
  end
  def create
    @game = Game.new(params[:game])
    @game.opened=true
    @game.user_id = current_user.id
    create!
  end

  def update
    params[:game][:user_id]=current_user.id
    update!
  end

  def open
    Game.find_by_id(params[:game_id].to_i).open
    redirect_to admin_games_path, notice: '开放比赛成功！'
  end

  def close
    Game.find_by_id(params[:game_id].to_i).close
    redirect_to admin_games_path, notice: '关闭比赛成功！'
  end

  def start
    session[:current_game_id] = params[:game_id]
    redirect_to admin_games_path, notice: '设定当前比赛成功！'
  end

  def finish
    session[:current_game_id] = nil
    redirect_to admin_games_path, notice: '当前比赛已结束！'
  end

  def destroy
    rounds = Round.where(game_id: params[:id].to_i)
    unless rounds.blank?
      rounds.each do |round|
        unless round.result == -1  then
          round.user.scores = round.user.scores - round.score
          # 根据用户积分，重新计算等级
          round.user.grade = Level.fetch_grade(round.user.scores)
          round.user.save
        end
        round.destroy
      end
    end

    game = Game.find(params[:id])
    game.destroy


    redirect_to :back

  end

end

app/controllers/newadmin/games_controller.rb
class Newadmin::GamesController < NewadminController
  inherit_resources
  respond_to :html, :json
  def index
    # hash = {}
    # hash[:city] = params[:city] unless params[:city].blank?
    # @games = Game.where(hash).order('updated_at desc').page(params[:page]).per(20)
  end

  def show
    redirect_to action: "index"
  end

  def create
    @game = Game.new(params[:game])
    @game.opened=true
    @game.user_id = current_user.id
    create!
  end

  def update
    params[:game][:user_id]=current_user.id
    update!
  end

  def open
    Game.find_by_id(params[:game_id].to_i).open
    redirect_to admin_games_path, notice: '开放比赛成功！'
  end

  def close
    Game.find_by_id(params[:game_id].to_i).close
    redirect_to admin_games_path, notice: '关闭比赛成功！'
  end

  def start
    session[:current_game_id] = params[:game_id]
    redirect_to admin_games_path, notice: '设定当前比赛成功！'
  end

  def finish
    session[:current_game_id] = nil
    redirect_to admin_games_path, notice: '当前比赛已结束！'
  end

  def destroy
    rounds = Round.where(game_id: params[:id].to_i)
    unless rounds.blank?
      rounds.each do |round|
        unless round.result == -1  then
          round.user.scores = round.user.scores - round.score
          # 根据用户积分，重新计算等级
          round.user.grade = Level.fetch_grade(round.user.scores)
          round.user.save
        end
        round.destroy
      end
    end

    game = Game.find(params[:id])
    game.destroy


    redirect_to :back

  end

  def view_applications
    @game = Game.find(params[:id])
    render :json => { :content => render_to_string(:partial => "newadmin/games/view_applications") }
  end

end

app/helpers/games_helper.rb
module GamesHelper
  def gameUrl game
    url= "/activities/#{ymd(game.date)}/#{game.url}/"
    title= "#{truncate(strip_tags(game.introduction), :length => 60, :omission => '...')}"
    body= "#{game.city}-#{game.place}-#{game.date}"
    body+= " Coming Soon..." if game.date > Date.today
    url= "<a href=\"#{url}\" target=\"_blank\" title=\"#{title}\">#{body}</a>"
  end

  def recommend_gameUrl? gv_id
    game = GameVedio.find(gv_id).game
    url= "/activities/#{ymd(game.date)}/#{game.url}/"
    title= "更多-#{game.date}－#{game.city}-#{game.place}活动..."
    url= "<a href=\"#{url}\" target=\"_blank\" title=\"#{title}\">#{title}</a>"
  end

  def check_score?(game_vedio_id)
    flag = false
    gv = GameVedio.find_by_sql("select count(*) as count from game_vedios v where v.id in
        (select game_vedio_id from game_records where game_vedio_id=#{game_vedio_id} and
        user_id=#{current_user.id} and score=0) and v.created_at > date_sub(now(),interval 7 day)").first
    flag = (gv.count > 0)
    flag
  end

  def goals_panna_kt?
      goals = Round.where("user_id = ?",current_user.id).map(&:goals).sum
      kt = Round.where("user_id =#{current_user.id} and panna_ko = true").count
      pannas = Round.where("user_id=#{current_user.id} ").map(&:pannas).sum
      "个人累计进球数：#{goals} 个人累计KT数：#{kt} 个人累计穿裆: #{pannas}"
  end

end

app/helpers/newadmin/games_helper.rb
module Newadmin::GamesHelper
end

app/views/admin/games/_form.html.slim
= javascript_include_tag 'ckeditor/init'
= form_for [:admin, @game] do |f|
  - if @game.errors.any?
    #error_explanation
      h2 = "#{pluralize(@game.errors.count, "error")} prohibited this game from being saved:"
      ul
        - @game.errors.full_messages.each do |message|
          li = message
  .field
    = f.label "名称"
    = f.text_field :name
  .field
    = f.label "所属俱乐部"
    = f.select :club_id, Club.all.map { |club| [club.name,club.id] }, include_blank: false

  .field
    = f.label "URL"
    = f.text_field :url
    | 
      必填项，例子：shanghai-midi-music-festival 或者 shanghai-midi-yinyuejie
  .field
    = f.label "Level"
    = f.select(:priority, options_for_select((0..9).to_a, @game.priority) ) 
    |  显示优先顺序，值高的靠前显示
  .field
    = f.label "国家"
    = f.select(:country, options_for_select(Country.countries.map(&:name),@game.country))
  .field
    = f.label '城市'
    = f.select(:city, options_for_select(Country.cities.map(&:name),@game.city) )
  .field
    = f.label "地点"
    = f.text_field :place
  .field
    = f.label "经纬度"
    = f.text_field :location
    |  
    = link_to "去百度地图获取经纬度","http://api.map.baidu.com/lbsapi/getpoint/index.html",:target => "_blank"


  /!.field
    /!= f.label '日期'
    /!= f.date_select :date
  .field
    = f.label '开始时间'
    = f.date_select :time_start
  .field
    = f.label '结束时间'
    = f.date_select :time_end
  .field
    = f.label '图片'
    = f.file_field :avatar
  .field
    = f.label "APP端:比赛详细介绍"
    br
    == f.text_area :introduction, :size => '100x3'
  .field
    = f.label "APP端:比赛交通说明"
    br
    = f.text_area :traffic_intro, :size => '100x3'
  .field
    = f.label "APP端:比赛周边信息介绍"
    br
    = f.text_area :arround_intro, :size => '100x3'
  .field
    = f.label "网站：比赛详细介绍"
    br
    = cktext_area_tag("game[site_introduction]", "#{@game.site_introduction}", :height => 150)
  .field
    = f.label "网站：比赛交通说明"
    br
    = cktext_area_tag("game[site_traffic]", "#{@game.site_traffic}", :height => 150)
  .field
    = f.label "网站：比赛周边信息介绍"
    br
    = cktext_area_tag("game[site_arround]", "#{@game.site_arround}", :height => 150)
  .actions = f.submit '保存'

app/views/admin/games/edit.html.slim
h1 编辑比赛
= link_to '显示', [:admin, @game]
||
= link_to '后退', admin_games_path

== render 'form'

app/views/admin/games/index.html.slim
span
  = link_to '新建比赛', new_admin_game_path
span style='padding-left: 20px;'
  = link_to '管理国家地区', admin_countries_path
span style='padding-left: 20px;'
  = link_to '绑定优酷视频帐号', '/users/auth/youku'
span style='padding-left: 20px;'
  == "已绑定账户(#{link_to @new_plant.youku_username, @new_plant.youku_info.try(:link), target: '_blank'} )"

= form_tag admin_games_path, method: :get do
  = label_tag '城市：'
  = select_tag(:city, options_for_select(Country.cities.map(&:name)) )
  = submit_tag '搜索'
  
table
  tr
    th 国家
    th Level
    th URL
    th 城市
    th 名称
    th 俱乐部
    th 地点
    th 开始
    th 结束
    th 参赛人数
    th 当前比赛
    th 开放比赛
    th colspan="3"
    
  - @games.each do |game|
    tr
      td = text_field_tag(:country,game.country, :disabled => true,:size => 7)
      td = text_field_tag(:priority,game.priority, :disabled => true,:size => 3)
      td = text_field_tag(:url,game.url, :disabled => true,:size => 15)
      td = text_field_tag(:city,game.city, :disabled => true,:size => 7)
      td = text_field_tag(:city,game.name, :disabled => true,:size => 15)
      td = text_field_tag(:city,game.club.try(:name), :disabled => true,:size => 8)
      td = text_field_tag(:place,game.place, :disabled => true)
      td = text_field_tag(:date,game.time_start, :disabled => true,:size => 12)
      td = text_field_tag(:time,game.time_end, :disabled => true,:size => 12)    
      td = game.rounds.count
      td
        - unless @current_game == game
          = button_to '设置为当前比赛', admin_games_start_path(game, game_id: game.id)
        - else
          = button_to '取消为当前比赛', admin_games_finish_path(game)
      td
        - unless game.opened
          = button_to '开放比赛', admin_games_open_path(game_id: game.id)
        - else
          = button_to '关闭比赛', admin_games_close_path(game_id: game.id)
      td = link_to '显示', [:admin, game]
      td = link_to '编辑', edit_admin_game_path(game)
      td = link_to '删除', [:admin, game], confirm: '你确定么？', method: :delete
= paginate @games

app/views/admin/games/new.html.slim
h1 新建比赛
= link_to '后退', admin_games_path

== render 'form'

app/views/admin/games/show.html.slim
div style="overflow: hidden; zoom: 1;"
  div style="float: left;"
    p#notice = notice
    = link_to '编辑', edit_admin_game_path(@game)
    ||
    = link_to '后退', admin_games_path
    p
      string 名称:
      = @game.name
    p
      string 所属俱乐部:
      = @game.club.try(:name)
    p
      string URL:
      = @game.url
    p
      strong 国家：
      = @game.country
    p
      strong 城市：
      = @game.city
    p
      strong 地点：
      = @game.place
    p
      strong 经纬度：
      = @game.location
    p
      strong 开始时间：
      = @game.time_start.strftime('%Y-%m-%d')
    p
      strong 结束时间：
      = @game.time_end.strftime('%Y-%m-%d')
    p
      strong 比赛详细介绍：
      br
      = raw @game.site_introduction
    .clear
    p
      strong 比赛交通说明：
      br
      = raw @game.site_traffic
    .clear
    p
      strong 比赛周边信息介绍：
      br
      = raw @game.site_arround
    .clear
  / div style="float: left; margin-left:60px; margin-top: 30px; width: 640px; "
  /   table style="width: 640px;"
  /     tr
  /       th ID
  /       th 标题
  /       th 积分
  /       th 积分
  /       th 积分
  /       th 积分
  /       th 积分
  /       th 积分
  /     - 10.times do
  /       tr
  /         td 123
  /         td 456sfkljslkjfd
  /         td 789sfkljjkfdsfs
  /         td 789dsflkffs
  /         td 789dlkfsdkklfsdkfl;
  /         td 789fskljsjfsk
  /         td 789flkfklkjlfsjksklj
  /         td 789sfkldjfjsf