config/routes.rb
Kicktempo::Application.routes.draw do
  captcha_route
  mount Ckeditor::Engine => '/ckeditor'
  
  mount ChinaCity::Engine => '/china_city'

  match 'newhome/:action' => 'newhome', via: [:get,:post]
  match 'my/:action' => 'my', via: [:get,:post]

  resources :game_albums do
    collection do
      get 'face'
      get 'show/:user_id' => 'game_albums#show'
      put 'upload_face'
    end
  end
  resources :leagues do

    collection do
      post :search_friends
      post :invite
      get  :invite_check
      get  :check_name
      post :update_league
      get  'ignore/:id'=> 'leagues#ignore',as: :ignore
      get  'accept/:id'=> 'leagues#accept',as: :accept
      post :accept
    end
  end
  get  'my_leagues'=>'leagues#my_leagues', as: :my_leagues
  #get 'game_albums/face'

  get "autodata/index"

  get  '/games' => 'games#index'
  get  '/games/list' => 'games#list'
  post '/games/registration' => 'games#registration'
  get  '/games/terms' => 'games#game_terms', as: :game_terms
  get  '/games/rank' => 'games#rank'
  get  '/games/scores_list'=> 'games#scores_list'
  get  '/games/league_scores_list'=> 'games#league_scores_list'
  get  '/games/next_vedio' => 'games#slide'
  get  '/games/one_next_vedio' => 'games#one_slide'
  get  '/games/check_score'
  put  '/games/score'
  get  '/bags/search' => 'bags#search'

  get  '/games/show' => 'games#show'
  post  '/games/join' => 'games#join'
  post  '/games/invite' => 'games#invite'


  match '/activities/:year/:month/:day/:url/' => 'games#scene', :constraints => { :url => /.+/ }, via: [:get,:post]

  get  '/new_plant' => 'new_plant#index'
  get  '/about_us' => 'new_plant#about_us'
  get  '/support_our_plant' => 'new_plant#support_our_plant'
  get  '/kicktempo_story' => 'new_plant#kicktempo_story'
  get  '/school_list' => 'new_plant#school_list'
  get  '/donate' => 'new_plant#donate'
  get  '/donated_citys' => 'new_plant#donated_citys'
  get  '/donated_schools' => 'new_plant#donated_schools'
  get  '/plant_news' => 'new_plant#plant_news'
  get  'support_kicktempo' => 'new_plant#support_kicktempo'
  get  'gas_intro' => 'new_plant#gas_intro'
  get  'company' => 'new_plant#company'
  post 'send_message' => 'new_plant#send_message'
  post 'send_donate_message' => 'new_plant#create_donate_message'

  get  '/confirm_phone' => 'users#confirm_phone', as: :confirm_phone
  get  '/invite' => 'users#invite', as: :invite
  get  '/connect_auths' => 'users#connect_auths', as: :connect_auths
  get  '/subscribe_sms' => 'users#subscribe_sms', as: :subscribe_sms
  get  '/myorders' => 'users#myorders', as: :myorders
  get  '/myclubbers/:type/:manager' => 'users#myclubbers', as: :myclubbers
  post '/varify_phone' => 'users#varify_phone', as: :varify_phone
  post '/varify_subscribe_sms' => 'users#varify_subscribe_sms', as: :varify_subscribe_sms
  get  '/send_varification_code' => 'users#send_code', as: :send_code
  post '/varify_code' => 'users#varify_code', as: :varify_code
  get  '/my_space' => 'users#myspace', as: :myspace
  get  '/user/:user_id' => 'users#home', as: :user_home
  get  '/shows/my' => 'game_vedios#my_shows', as: :my_shows
  get  '/shows/:id' => 'game_vedios#show'
  get  '/my_scores' => 'users#my_scores'
  #get  '/user/:user_id/game_vedios' => 'game_vedios#index', as: :user_game_vedios

  match '/users/auth/Youku/callback(.:format)' => 'admin/admission#set_youku', via: [:get,:post]

  devise_for :users, controllers: {
    sessions:           :sessions,
    omniauth_callbacks: :authentications,
    registrations: :registrations
  }

  devise_scope :user do
    #get '/sign_up' => "registrations#new", as: :sign_up
    get '/sign_in' => "devise/sessions#new", as: :sign_in
    get '/sign_out' => "devise/sessions#destroy", as: :sign_out
    post  '/sign_up'  => 'registrations#create'
    post '/get_authcode' => 'registrations#get_authcode'
    put '/authuser_update' => 'registrations#authuser_update', as: :authuser_update
  end

  # weixin
  get '/wx_callback' => "weixin/weixin_api#callback_get"
  post '/wx_callback' => "weixin/weixin_api#callback_post"
  get '/weixin/train' => "weixin/pages#train"

  resources :clubs

  namespace :api do
    resources :users, only: [] do
      get 'vedios', on: :member
      collection do
        get 'user_info'
        post 'login'
        post 'sign_up'
        get 'base_info'
        post 'update_profile'
        post 'auth_connect'
        post 'share'
        get 'auth_info'
        get 'auth_redirect_uri'
        post 'oauth_login'
        post 'oauth_signup'
      end
    end

    resources :games, only: [:index, :show] do
      collection do
        post 'post_score'
        get 'citys'
        get 'countrys'
        get 'country_cities'
        get 'rank'
        get 'page_rank'
        get 'page_league_rank'
        post 'create_game'
        post 'post_league'
        get 'city_games'
        post 'bag_trace'
        post 'post_face'
      end
    end

    resources :admin, only: [] do
      get 'youku_token', on: :collection
      get 'refresh_youkutoken', on: :collection
    end

    resources :articles, only: [:index, :show] do
      get 'game_intro', on: :collection
      get 'game_terms', on: :collection
    end

    resources :game_vedios, only: [:index, :show] do
      post 'post_vedio', on: :collection
    end
  end

  namespace :weixin do
    get 'w_services/get_gz_reply_content' => 'w_services#get_gz_reply_content'
    get 'w_services/get_auto_reply_content' => 'w_services#get_auto_reply_content'

    resources :w_services do
      member do
        get 'first_gz'
        get 'auto_reply'
      end
    end

    match 'w_replies/get_reply_content' => 'w_replies#get_reply_content', via: [:get]
    resources :w_replies

    resources :w_users do
      get 'unbind', on: :member
    end
    resources :materials do
      get 'preview', on: :member
    end
    resources :multiple_materials do
      get 'edit_list', on: :member
      post 'update_list', on: :member
      get 'preview', on: :member
    end
    resources :multiple_material_lists do
      get 'preview', on: :member
    end
    resources :audio_materials
    resources :w_questions
    resources :w_question_answers

    resources :w_menus do
      get 'sync', on: :collection
    end
    resources :w_cities
    resources :w_media
    resources :w_brands

    match 'users/:action' => 'users', via: [:get,:post]
    match 'pages/:action' => 'pages', via: [:get,:post]

  end
  get '/weixin/w_users/:id/unbind' => 'weixin/w_users#unbind'
  get '/time' => 'home#time'
  
  namespace :newadmin do
    resources :games do
      get 'view_applications', on: :member
    end
    resources :kt_errors do
      get 'solve', on: :member
    end
    resources :online_courses
    resources :students
    resources :coaches

    resources :donate_messages
    resources :school_items
    resources :companies
    resources :albums do
      get 'upload', on: :member
      post 'upload', on: :member
    end
    resources :articles
  end

  namespace :admin do
    get  '/index' => 'home#index'
    resources :games
    resources :gifts
    resources :orders
    resources :rounds
    resources :messages
    resources :donate_messages
    resources :companies
    resources :school_locals
    resources :school_items
    resources :countries
    resources :clubs
    resources :bags
    resources "bag_traces"
    resources :albums do
      resources :pictures, only: [] do
        get 'multi_edit', as: :multi_edit, on: :collection
        post 'multi_update', as: :multi_update, on: :collection
      end
    end
    resources :pictures do
      collection do
        get 'uploads', as: :uploads
      end
    end

    post '/games/open'
    post '/games/close'
    post '/games/start'
    post '/games/finish'

    get  '/users' => 'users#index'
    get  '/users/search' => 'users#search'
    get  '/users/profile' => 'users#profile'
    get  '/users/subscribed_sms'  => 'users#subscribed_sms'
    get  '/users/unsubscribed_sms'  => 'users#unsubscribed_sms'
    post  '/users/cancel_subscribed_sms'  => 'users#cancel_subscribed_sms'
    post  '/users/confirm_subscribed_sms'  => 'users#confirm_subscribed_sms'
    get  '/users/agent_list' => 'users#agent_list'
    get  '/users/judge_list' => 'users#judge_list'

    post  '/users/check_sms'  => 'users#check_sms'
    post  '/users/uncheck_sms'  => 'users#uncheck_sms'
    post  '/users/selected_sms'  => 'users#selected_sms'
    post  '/users/cancel_selected_sms'  => 'users#cancel_selected_sms'


    post '/users/admin' => 'users#admin'
    get '/users/setjudge' => 'users#setjudge'
    put '/users/judge' => 'users#judge'
    get '/users/setagent' => 'users#setagent'
    put '/users/agent' => 'users#agent'
    get  '/users/new' => 'users#new'
    get  '/users/tally' => 'users#tally'
    get  '/users/day_top_scores' => 'users#day_top_scores'
    get  '/users/day_rounds' => 'users#day_rounds'
    get  '/users/day_goals' => 'users#day_goals'
    get  '/users/day_games' => 'users#day_games'
    post '/users' => 'users#create'
    post '/users/registration' => 'users#registration'
    post '/users/admission' => 'users#admission'
    post '/users/phone' => 'users#phone'
    post '/users/area' => 'users#area'
    post '/users/destroy' => 'users#destroy'
    post '/users/batch_signup' => 'users#batch_signup'
    get '/users/batch_index' => 'users#batch_index'
    get '/users/setvip' => 'users#setvip'
    put '/users/updatevip' => 'users#updatevip'
    get '/users/cancelvip' => 'users#cancelvip'

    get  '/admission' => 'admission#index'
    post '/admission/admit' => 'admission#admit'
    get  '/admission/entered' => 'admission#entered'

    get  '/scores' => 'scores#index'
    post '/scores/submit' => 'scores#submit'
    get  '/scores/list' => 'scores#list'

    get '/levels' => 'levels#index'
    get '/levels/rules' => 'levels#rules'


    get '/articles/:id/set_visit' => 'articles#set_visit'

    resources :articles
    resources :new_plants

    resources :info_urls

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index
  end
end

app/controllers/home_controller.rb
# -*- coding: utf-8 -*-
class HomeController < ApplicationController

  def index
    @slides = InfoUrl.where(usage: 'index_slide',status:true).order("priority desc")
    @shows = InfoUrl.where(usage: 'index_show')
    case Rails.env
    when 'development'
      if request.host == 'rice.local' && params[:controller] == 'home' && params[:action] == 'index'
        load_2026_resourse
        render 'new_plant/index'
      end
    when 'production'
      if (request.host == '2026.kicktempo.cn' || request.host == '2026.ktfootball.com') && params[:controller] == 'home' && params[:action] == 'index'
        load_2026_resourse
        render 'new_plant/index'
      end
    else
      render 'home/index'
    end
  end

  def terms
  end

  def join_us
  end

  def business
  end

  def kt
    @page_title="关于KT足球"
    @nav="kt"
  end
  def navAsyn
    @section = params[:section]
    @shows = InfoUrl.where(usage: "nav_#{@section}")
    #games
    @fgames   = Game.where("date>='#{Time.new.strftime("%Y-%m-%d")}'") if "forecast" == @section
    @rgames   = Game.where("date<='#{Time.new.strftime("%Y-%m-%d")}'").order("date desc") if "review" == @section
    #rank
    @scores = User.where("id != ?",123).order("scores desc").limit(10) if "rank1"== @section
    # 老的算法抛弃
    # @scores = User.all(:conditions => ["id != ?", 123], limit: 10, order: 'scores DESC') if "rank1"== @section
    @scores = League.all(:conditions => ["league_type = ? and status=?", League::LEAGUE_TYPES_STEADY,1], limit: 10, order: 'scores DESC') if "rank2"== @section
    @judges   = JudgeRank.order("scores desc").page(params[:page]).per(10) if "judge_ranks" == @section
    @gifts    = Gift.where("category = 0") if "exchange"== @section
    @gifts    = Gift.where("category = 1") if "buy"== @section
    respond_to do |format|
      format.js
    end
  end

  def plan_2026;@page_title="2026计划";@nav="plan";end

  def agent_scopes
    @page_title="2026计划--布点城市";
    @nav="plan"
    @users = User.find_by_sql("select city,count(id) as count from users where city != '' group by city order by count desc limit 5")
    @agent_users = User.where("agent=1")
    #UserProfile.cities?
  end

  def agent_reports
    day= Time.new.strftime("%Y-%m-%d")
    reports = AgentReport.where(city: params[:city],day: day)
    render json: reports.collect{|r| "#{day} #{r.city}统计 总球员数#{r.reg_count}  其中代理#{r.user.nickname}球员人数#{r.invitees_count}"}
  end
  def game;@page_title="赛事信息";@nav="game";end
  def exchange
    @gifts = Gift.where("category=0")
  end
  def buy
    @gifts = Gift.where("category=1")
  end
  def rank
    @page_title="积分榜 一VS一"
    @nav="rank"
    #@scores = User.all(:conditions => ["id != ?", 123], limit: 10, order: 'scores DESC')
  end
  def judge_ranks
    @page_title="积分榜 裁判积分榜"
    @nav="rank"
    @judges = JudgeRank.where("").order("scores desc").page(params[:page]).per(10)
  end
  def rank1
    @page_title="积分榜 一VS.一"
    @nav="rank"
    @scores = User.all(:conditions => ["id != ?", 123], limit: 10, order: 'scores DESC')
  end
  def rank2
    @page_title="积分榜 二VS.二"
    @nav="rank"
    @scores = League.all(:conditions => ["league_type = ? and status=?", League::LEAGUE_TYPES_STEADY,1], limit: 10, order: 'scores DESC')
  end
  def cooperate;@nav="cooperate";end
  def agency;@nav="agency";end

  def time

  end

  private
  def load_2026_resourse
    @shows = InfoUrl.where(usage: '2026_intro').limit(2)
    @supports_count = NewPlant.where(indentify: 'kicktempo_2026_info').first.try(:support_counter).to_i
    get_new_plant
  end
end

app/helpers/home_helper.rb
# -*- coding: utf-8 -*-
module HomeHelper

  def achievements?
    "累计胜场："+Round.where(:user_id=>"#{current_user.id}",:result => 1).count.to_s <<
       " 平场：" <<
       Round.where(:user_id=>"#{current_user.id}",:result=> 0).count.to_s <<
       " 负场：" <<
       Round.where(:user_id=>"#{current_user.id}",:result=> -1).count.to_s
  end

  def invitees_count?(inviter)
    inviter.present? ? inviter.invitees_count : "0"
  end

  def lives_count?(inviter)
    inviter.present? ? inviter.lives_count : "0"
  end
end

app/views/home/agency.html.slim
.clear
div id='agency_div' 
  javascript:
     navAsyn('/navAsyn','kt_qichang')

.clear

app/views/home/agent_scopes.html.slim
div id='plan_div' 
    h2.np-gold style='margin: 0 0 10px 30px;' 布点城市

    #map
     = image_tag 'map.png'
     = render partial: '/home/plan/province', :as => :user, collection: @agent_users


    #school_lists.formregion
      .loading.np-gold Loading
      = render partial: 'shared/close_btn'
      p.np-gold 代理球员统计
      #citys.formregion
      

    .clear

     #games_rank_list.game_rank.word_container
      h5 style='float:left' 城市榜
      div#ranking-list
        table.game_ranks
           tr.header
              th.ranks 排名
              th.city 城市
              th.count 人数
           - @users.each_with_index do |user,index|
            tr.users 
                 td.ranks = index +1
                 td.city = user.city
                 td.count = user.count
.clear

app/views/home/business.html.slim
div
  fieldset.devise style="width: 80%;"
    legend 诚招全国代理与合作
    br
    p KickTempo专利产品，是中国首款KT足球专业场地，成功打破传统足球场地限制。潮流运动、炫酷体验、随时随地、自由挥洒
    br
    | <p>一款安全便携的充气球场 + 一种颠覆传统的商业模式 = 一个潜力巨大的<font color='blue'>蓝海</font>市场</p>
    p 产品＋赛事一体化运营 
    p 体育＋公益互动式营销
    p 垂询热线  (86)021 - 5643 5766
    br
    = link_to "什么是气场","articles/33",:target=>"_blank"
    br
    = link_to "代理资料下载","/articles/38",:target=>"_blank"
    br
    = link_to "代理商申请表下载", "http://pan.baidu.com/share/link?shareid=389514&uk=2215688906",:target=>"_blank"
    br
    = link_to "代理商方案","/articles/43",:target=>"_blank"
    br
    = link_to "KT足球媒体报道","/articles/30",:target=>"_blank"
       
div align='center' valign='middle'
       | <iframe height=498 width=510 src="http://player.youku.com/embed/XNTM1MTEyNzMy" frameborder=0 allowfullscreen></iframe>
                
br
.clear

app/views/home/buy.html.slim
.clear
div id='game_div' 
   = render :partial => '/home/rank/buy'

.clear
             

app/views/home/cooperate.html.slim
div
  fieldset.devise style="width: 80%;"
    legend 诚招全国代理与合作
    br
    p KickTempo专利产品，是中国首款KT足球专业场地，成功打破传统足球场地限制。潮流运动、炫酷体验、随时随地、自由挥洒
    br
    | <p>一款安全便携的充气球场 + 一种颠覆传统的商业模式 = 一个潜力巨大的<font color='blue'>蓝海</font>市场</p>
    p 产品＋赛事一体化运营 
    p 体育＋公益互动式营销
    p 垂询热线  (86)021 - 5643 5766
    br
    = link_to "什么是气场","articles/33",:target=>"_blank"
    br
    = link_to "代理资料下载","/articles/38",:target=>"_blank"
    br
    = link_to "代理商申请表下载", "http://pan.baidu.com/share/link?shareid=389514&uk=2215688906",:target=>"_blank"
    br
    = link_to "代理商方案","/articles/43",:target=>"_blank"
    br
    = link_to "KT足球媒体报道","/articles/30",:target=>"_blank"
       
div align='center' valign='middle'
       | <iframe height=498 width=510 src="http://player.youku.com/embed/XNTM1MTEyNzMy" frameborder=0 allowfullscreen></iframe>
                
br
.clear

app/views/home/game.html.slim
.clear
div id='game_div' 
   javascript:
     navAsyn('/navAsyn','forecast')

.clear

app/views/home/index.html.slim
#slides_container
  /* #ribbon = image_tag "slides/new-ribbon.png"
  /* #frame  = image_tag "slides/frame.png"
  #slides
    .slides_container
      - @slides.each do |slide|
        .slide
          - if slide.article_link.blank?
            = image_tag("#{slide.url}", :size => "720x300", :alt => "#{slide.title}")
          - else
            = link_to image_tag("#{slide.url}", :size => "720x300", :alt => "#{slide.title}"), slide.article_link,:target=>"_blank"
          .caption
            p
              = link_to slide.description, slide.article_link

#shows_container
  - @shows.each do |show|
    .show
      - if show.article_link.blank?
        = image_tag("#{show.url}", :size => "220x138", :alt => "#{show.title}")

        .show_title
          h5 = show.title
        .show_desc
          pre = show.description

      - else
        = link_to image_tag("#{show.url}", :size => "220x138", :alt => "#{show.title}"), show.article_link,:target=>"_blank"
        .show_title
          h5 = link_to show.title, show.article_link, :style => 'color: #CCCC00;font-weight:bold;',:target=>"_blank"
        .show_desc
          pre = raw show.description
  .clear

.goal
  h3 目标：2015年1月1日 —— 100万足球爱好者
  p
    |已经累计有
    span = User.count
    |个用户加入！爱足球的心！加入进来享受你的专属魅力足球！
- unless current_user
  = link_to (image_tag 'join_now.png', id: 'join_now'), sign_up_path

app/views/home/join_us.html.slim
javascript:
   window.location='articles/39'

app/views/home/kt.html.slim
.clear
div id='kt_div' 
  javascript:
     navAsyn('/navAsyn','kt')

.clear

app/views/home/plan_2026.html.slim
.clear
div id='plan_div' 
  javascript:
     navAsyn('/navAsyn','basics')

.clear

app/views/home/rank.html.slim
.clear
div id='rank_div' 
  javascript:
     navAsyn('/navAsyn','rank1')

.clear

app/views/home/time.html.slim
= image_tag "calendar.jpg", style: "width:100%; padding-bottom: 12px;"