config/routes.rb
Kicktempo::Application.routes.draw do
  captcha_route
  mount Ckeditor::Engine => '/ckeditor'
  
  mount ChinaCity::Engine => '/china_city'

  match 'newhome/:action' => 'newhome', via: [:get,:post]
  match 'my/:action' => 'my', via: [:get,:post]

  resources :game_albums do
    collection do
      get 'face'
      get 'show/:user_id' => 'game_albums#show'
      put 'upload_face'
    end
  end
  resources :leagues do

    collection do
      post :search_friends
      post :invite
      get  :invite_check
      get  :check_name
      post :update_league
      get  'ignore/:id'=> 'leagues#ignore',as: :ignore
      get  'accept/:id'=> 'leagues#accept',as: :accept
      post :accept
    end
  end
  get  'my_leagues'=>'leagues#my_leagues', as: :my_leagues
  #get 'game_albums/face'

  get "autodata/index"

  get  '/games' => 'games#index'
  get  '/games/list' => 'games#list'
  post '/games/registration' => 'games#registration'
  get  '/games/terms' => 'games#game_terms', as: :game_terms
  get  '/games/rank' => 'games#rank'
  get  '/games/scores_list'=> 'games#scores_list'
  get  '/games/league_scores_list'=> 'games#league_scores_list'
  get  '/games/next_vedio' => 'games#slide'
  get  '/games/one_next_vedio' => 'games#one_slide'
  get  '/games/check_score'
  put  '/games/score'
  get  '/bags/search' => 'bags#search'

  get  '/games/show' => 'games#show'
  post  '/games/join' => 'games#join'
  post  '/games/invite' => 'games#invite'


  match '/activities/:year/:month/:day/:url/' => 'games#scene', :constraints => { :url => /.+/ }, via: [:get,:post]

  get  '/new_plant' => 'new_plant#index'
  get  '/about_us' => 'new_plant#about_us'
  get  '/support_our_plant' => 'new_plant#support_our_plant'
  get  '/kicktempo_story' => 'new_plant#kicktempo_story'
  get  '/school_list' => 'new_plant#school_list'
  get  '/donate' => 'new_plant#donate'
  get  '/donated_citys' => 'new_plant#donated_citys'
  get  '/donated_schools' => 'new_plant#donated_schools'
  get  '/plant_news' => 'new_plant#plant_news'
  get  'support_kicktempo' => 'new_plant#support_kicktempo'
  get  'gas_intro' => 'new_plant#gas_intro'
  get  'company' => 'new_plant#company'
  post 'send_message' => 'new_plant#send_message'
  post 'send_donate_message' => 'new_plant#create_donate_message'

  get  '/confirm_phone' => 'users#confirm_phone', as: :confirm_phone
  get  '/invite' => 'users#invite', as: :invite
  get  '/connect_auths' => 'users#connect_auths', as: :connect_auths
  get  '/subscribe_sms' => 'users#subscribe_sms', as: :subscribe_sms
  get  '/myorders' => 'users#myorders', as: :myorders
  get  '/myclubbers/:type/:manager' => 'users#myclubbers', as: :myclubbers
  post '/varify_phone' => 'users#varify_phone', as: :varify_phone
  post '/varify_subscribe_sms' => 'users#varify_subscribe_sms', as: :varify_subscribe_sms
  get  '/send_varification_code' => 'users#send_code', as: :send_code
  post '/varify_code' => 'users#varify_code', as: :varify_code
  get  '/my_space' => 'users#myspace', as: :myspace
  get  '/user/:user_id' => 'users#home', as: :user_home
  get  '/shows/my' => 'game_vedios#my_shows', as: :my_shows
  get  '/shows/:id' => 'game_vedios#show'
  get  '/my_scores' => 'users#my_scores'
  #get  '/user/:user_id/game_vedios' => 'game_vedios#index', as: :user_game_vedios

  match '/users/auth/Youku/callback(.:format)' => 'admin/admission#set_youku', via: [:get,:post]

  devise_for :users, controllers: {
    sessions:           :sessions,
    omniauth_callbacks: :authentications,
    registrations: :registrations
  }

  devise_scope :user do
    #get '/sign_up' => "registrations#new", as: :sign_up
    get '/sign_in' => "devise/sessions#new", as: :sign_in
    get '/sign_out' => "devise/sessions#destroy", as: :sign_out
    post  '/sign_up'  => 'registrations#create'
    post '/get_authcode' => 'registrations#get_authcode'
    put '/authuser_update' => 'registrations#authuser_update', as: :authuser_update
  end

  # weixin
  get '/wx_callback' => "weixin/weixin_api#callback_get"
  post '/wx_callback' => "weixin/weixin_api#callback_post"
  get '/weixin/train' => "weixin/pages#train"

  resources :clubs

  namespace :api do
    resources :users, only: [] do
      get 'vedios', on: :member
      collection do
        get 'user_info'
        post 'login'
        post 'sign_up'
        get 'base_info'
        post 'update_profile'
        post 'auth_connect'
        post 'share'
        get 'auth_info'
        get 'auth_redirect_uri'
        post 'oauth_login'
        post 'oauth_signup'
      end
    end

    resources :games, only: [:index, :show] do
      collection do
        post 'post_score'
        get 'citys'
        get 'countrys'
        get 'country_cities'
        get 'rank'
        get 'page_rank'
        get 'page_league_rank'
        post 'create_game'
        post 'post_league'
        get 'city_games'
        post 'bag_trace'
        post 'post_face'
      end
    end

    resources :admin, only: [] do
      get 'youku_token', on: :collection
      get 'refresh_youkutoken', on: :collection
    end

    resources :articles, only: [:index, :show] do
      get 'game_intro', on: :collection
      get 'game_terms', on: :collection
    end

    resources :game_vedios, only: [:index, :show] do
      post 'post_vedio', on: :collection
    end
  end

  namespace :weixin do
    get 'w_services/get_gz_reply_content' => 'w_services#get_gz_reply_content'
    get 'w_services/get_auto_reply_content' => 'w_services#get_auto_reply_content'

    resources :w_services do
      member do
        get 'first_gz'
        get 'auto_reply'
      end
    end

    match 'w_replies/get_reply_content' => 'w_replies#get_reply_content', via: [:get]
    resources :w_replies

    resources :w_users do
      get 'unbind', on: :member
    end
    resources :materials do
      get 'preview', on: :member
    end
    resources :multiple_materials do
      get 'edit_list', on: :member
      post 'update_list', on: :member
      get 'preview', on: :member
    end
    resources :multiple_material_lists do
      get 'preview', on: :member
    end
    resources :audio_materials
    resources :w_questions
    resources :w_question_answers

    resources :w_menus do
      get 'sync', on: :collection
    end
    resources :w_cities
    resources :w_media
    resources :w_brands

    match 'users/:action' => 'users', via: [:get,:post]
    match 'pages/:action' => 'pages', via: [:get,:post]

  end
  get '/weixin/w_users/:id/unbind' => 'weixin/w_users#unbind'
  get '/time' => 'home#time'
  
  namespace :newadmin do
    resources :games do
      get 'view_applications', on: :member
    end
    resources :kt_errors do
      get 'solve', on: :member
    end
    resources :online_courses
    resources :students
    resources :coaches

    resources :donate_messages
    resources :school_items
    resources :companies
    resources :albums do
      get 'upload', on: :member
      post 'upload', on: :member
    end
    resources :articles
  end

  namespace :admin do
    get  '/index' => 'home#index'
    resources :games
    resources :gifts
    resources :orders
    resources :rounds
    resources :messages
    resources :donate_messages
    resources :companies
    resources :school_locals
    resources :school_items
    resources :countries
    resources :clubs
    resources :bags
    resources "bag_traces"
    resources :albums do
      resources :pictures, only: [] do
        get 'multi_edit', as: :multi_edit, on: :collection
        post 'multi_update', as: :multi_update, on: :collection
      end
    end
    resources :pictures do
      collection do
        get 'uploads', as: :uploads
      end
    end

    post '/games/open'
    post '/games/close'
    post '/games/start'
    post '/games/finish'

    get  '/users' => 'users#index'
    get  '/users/search' => 'users#search'
    get  '/users/profile' => 'users#profile'
    get  '/users/subscribed_sms'  => 'users#subscribed_sms'
    get  '/users/unsubscribed_sms'  => 'users#unsubscribed_sms'
    post  '/users/cancel_subscribed_sms'  => 'users#cancel_subscribed_sms'
    post  '/users/confirm_subscribed_sms'  => 'users#confirm_subscribed_sms'
    get  '/users/agent_list' => 'users#agent_list'
    get  '/users/judge_list' => 'users#judge_list'

    post  '/users/check_sms'  => 'users#check_sms'
    post  '/users/uncheck_sms'  => 'users#uncheck_sms'
    post  '/users/selected_sms'  => 'users#selected_sms'
    post  '/users/cancel_selected_sms'  => 'users#cancel_selected_sms'


    post '/users/admin' => 'users#admin'
    get '/users/setjudge' => 'users#setjudge'
    put '/users/judge' => 'users#judge'
    get '/users/setagent' => 'users#setagent'
    put '/users/agent' => 'users#agent'
    get  '/users/new' => 'users#new'
    get  '/users/tally' => 'users#tally'
    get  '/users/day_top_scores' => 'users#day_top_scores'
    get  '/users/day_rounds' => 'users#day_rounds'
    get  '/users/day_goals' => 'users#day_goals'
    get  '/users/day_games' => 'users#day_games'
    post '/users' => 'users#create'
    post '/users/registration' => 'users#registration'
    post '/users/admission' => 'users#admission'
    post '/users/phone' => 'users#phone'
    post '/users/area' => 'users#area'
    post '/users/destroy' => 'users#destroy'
    post '/users/batch_signup' => 'users#batch_signup'
    get '/users/batch_index' => 'users#batch_index'
    get '/users/setvip' => 'users#setvip'
    put '/users/updatevip' => 'users#updatevip'
    get '/users/cancelvip' => 'users#cancelvip'

    get  '/admission' => 'admission#index'
    post '/admission/admit' => 'admission#admit'
    get  '/admission/entered' => 'admission#entered'

    get  '/scores' => 'scores#index'
    post '/scores/submit' => 'scores#submit'
    get  '/scores/list' => 'scores#list'

    get '/levels' => 'levels#index'
    get '/levels/rules' => 'levels#rules'


    get '/articles/:id/set_visit' => 'articles#set_visit'

    resources :articles
    resources :new_plants

    resources :info_urls

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :school_items
  validates :name, presence: true
  mount_uploader :logo, ImageUploader

  def image_path
    '/images/' + url
  end
end

app/controllers/admin/companies_controller.rb
# -*- coding: utf-8 -*-
class Admin::CompaniesController < AdminController
  inherit_resources

  def index
    @companys = Company.order('id DESC').page(params[:page]).per(20)
  end

  def create
    create! do |success, fail|
      success.html {
        redirect_to admin_companies_url
      }
    end
  end

  def update
    update! do |success, fail|
      success.html {
        redirect_to admin_companies_url
      }
    end
  end

end

app/controllers/newadmin/albums_controller.rb
class Newadmin::AlbumsController < NewadminController
  skip_before_filter :verify_authenticity_token, only: [:upload]

  inherit_resources
  def show
    redirect_to action: "index"
  end

  def create
    picture = Picture.new
    picture.avatar = params[:album][:cover]
    if picture.save
      Album.create :name => params[:album][:name],:cover => picture
      redirect_to action: "index"
    else
      flash[:alert] = picture.errors.full_messages.join(",")
      redirect_to action: "new"
    end
  end

  def update
    album = Album.find(params[:id])
    album.name = params[:album][:name]
    if params[:album][:cover]
      picture = Picture.new
      picture.avatar = params[:album][:cover]
      picture.save
      album.cover = picture
    end
    album.save
    redirect_to action: "index"
  end

  def upload
    if request.post?
      sharing_image = Picture.new(avatar: params[:Filedata],album_id: params[:id].to_i)
      if sharing_image.save
        render json: sharing_image.avatar(:middle)
      else
        return render :json => sharing_image.errors.messages.to_s
      end
    end
  end
end

app/controllers/newadmin/articles_controller.rb
class Newadmin::ArticlesController < NewadminController
  inherit_resources
  def show
    redirect_to "/newadmin/articles"
  end
end

app/controllers/newadmin/coaches_controller.rb
class Newadmin::CoachesController < NewadminController
  inherit_resources
  def show
    redirect_to action: "index"
  end
end

app/controllers/newadmin/companies_controller.rb
class Newadmin::CompaniesController < NewadminController
  inherit_resources
  def show
    redirect_to "/newadmin/companies?type=0"
  end
end

app/controllers/newadmin/donate_messages_controller.rb
class Newadmin::DonateMessagesController < NewadminController
  inherit_resources
  def show
    redirect_to action: "index"
  end
end

app/controllers/newadmin/games_controller.rb
class Newadmin::GamesController < NewadminController
  inherit_resources
  respond_to :html, :json
  def index
    # hash = {}
    # hash[:city] = params[:city] unless params[:city].blank?
    # @games = Game.where(hash).order('updated_at desc').page(params[:page]).per(20)
  end

  def show
    redirect_to action: "index"
  end

  def create
    @game = Game.new(params[:game])
    @game.opened=true
    @game.user_id = current_user.id
    create!
  end

  def update
    params[:game][:user_id]=current_user.id
    update!
  end

  def open
    Game.find_by_id(params[:game_id].to_i).open
    redirect_to admin_games_path, notice: '开放比赛成功！'
  end

  def close
    Game.find_by_id(params[:game_id].to_i).close
    redirect_to admin_games_path, notice: '关闭比赛成功！'
  end

  def start
    session[:current_game_id] = params[:game_id]
    redirect_to admin_games_path, notice: '设定当前比赛成功！'
  end

  def finish
    session[:current_game_id] = nil
    redirect_to admin_games_path, notice: '当前比赛已结束！'
  end

  def destroy
    rounds = Round.where(game_id: params[:id].to_i)
    unless rounds.blank?
      rounds.each do |round|
        unless round.result == -1  then
          round.user.scores = round.user.scores - round.score
          # 根据用户积分，重新计算等级
          round.user.grade = Level.fetch_grade(round.user.scores)
          round.user.save
        end
        round.destroy
      end
    end

    game = Game.find(params[:id])
    game.destroy


    redirect_to :back

  end

  def view_applications
    @game = Game.find(params[:id])
    render :json => { :content => render_to_string(:partial => "newadmin/games/view_applications") }
  end

end

app/controllers/newadmin/kt_errors_controller.rb
class Newadmin::KtErrorsController < NewadminController
  inherit_resources

  def index
    index! {
      if params[:is_solve].present?
        @collection = collection.where("is_solved = ?",params[:is_solve].to_i)
      elsif params[:klass].present?
        @collection = collection.where("klass = ?",params[:klass].to_i)
      else
        @collection = collection
      end
    }
  end

  def solve
    resource.update_attributes is_solved: true

    redirect_to admin_kt_errors_path :notice => "操作成功"
  end
end

app/controllers/newadmin/online_courses_controller.rb
class Newadmin::OnlineCoursesController < NewadminController
  inherit_resources
end

app/controllers/newadmin/school_items_controller.rb
class Newadmin::SchoolItemsController < NewadminController
  inherit_resources
  def show
    if resource.company_id.blank?
      redirect_to "/newadmin/school_items?type=0"
    else
      redirect_to "/newadmin/school_items?type=1"
    end
  end
end

app/controllers/newadmin/students_controller.rb
class Newadmin::StudentsController < NewadminController
  inherit_resources
  def show
    redirect_to action: "index"
  end
end

app/controllers/newadmin_controller.rb
# -*- coding: utf-8 -*-
class NewadminController < ApplicationController
  before_filter :must_logged_in
  before_filter :must_be_admin
  before_filter :set_current_game
  before_filter :get_new_plant
  after_filter :god_of_rescue_admin

  protected

  def must_be_admin
    return render :text => '你必须以管理员身份登录！' unless current_user.admin?
  end

  def set_current_game
    @current_game = Game.find(session[:current_game_id].to_i) unless session[:current_game_id].nil?
    @current_game ||= Game.first
  rescue
    session[:current_game_id] = nil
    @current_game = nil
  end

  def god_of_rescue_admin
  rescue => e
    return render :text => '数据出错，请重试。'
  end

end

app/helpers/newadmin/albums_helper.rb
module Newadmin::AlbumsHelper
end

app/helpers/newadmin/articles_helper.rb
module Newadmin::ArticlesHelper
end

app/helpers/newadmin/coaches_helper.rb
module Newadmin::CoachesHelper
end

app/helpers/newadmin/companies_helper.rb
module Newadmin::CompaniesHelper
end

app/helpers/newadmin/donate_messages_helper.rb
module Newadmin::DonateMessagesHelper
end

app/helpers/newadmin/games_helper.rb
module Newadmin::GamesHelper
end

app/helpers/newadmin/kt_errors_helper.rb
module Newadmin::KtErrorsHelper
end

app/views/newadmin/companies/_form.html.haml
= javascript_include_tag 'ckeditor/init'

= f.input :logo, as: :file
- if resource.logo.present?
  .input
    %label 已上传企业LOGO
    .fl
      = image_tag resource.logo.url,:size => "64"

= f.input :name
= f.input :site
= f.input :company_type
= f.input :donate_count

.input
  %label
    企业介绍
  .fl
    = f.input :intro, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} },label: false

.mt20
  = f.submit "提  交", class: "btn btn-primary"

:coffeescript
  $ ->
    setTimeout ->
      $("#sidebar").css("height",$("#main-container").height())
    ,2000

app/views/newadmin/companies/edit.html.haml
#main-container-title
  %span
    编辑企业
#main-container-body
  = render "shared/flash"

  = simple_form_for resource, url: newadmin_company_path(resource) do |f|
    = render partial: "form", locals: { f: f, ftype: :edit  }

app/views/newadmin/companies/index.html.haml
= stylesheet_link_tag "lib/fancybox/jquery.fancybox.css"
= javascript_include_tag "lib/fancybox/jquery.fancybox.js"

.font36.mt40.ml20
  资源管理
#main-container-title.clearfix{style: "height: 92px;"}
  %span.block.fl{style: "height: 48px; margin-top: 44px; border: none;"}
    = link_to "2026计划", newadmin_companies_path(type: 0),class: "grey9"
#main-container-body
  .clearfix
    .fl.pd20.w360.centerText.font20{class: request.url.include?("newadmin/companie") ? "byellow2" : "byellow1"}
      = link_to "捐赠企业名单管理", newadmin_companies_path(type: 0),class: "grey7"
    .fr.pd20.w360.centerText.font20{class: request.url.include?("newadmin/school_item") ? "byellow2" : "byellow1"}
      = link_to "受赠学校管理", newadmin_school_items_path(type: 0),class: "grey7"
  %ul.clearfix.mt20
    %li.fl
      = link_to "意向捐赠企业",newadmin_companies_path(type: 0),class: "block font20 grey6 pd10 bgreyf #{'border2' if params[:type] == '0'}",style: "border-bottom: none;"
    %li.fl
      = link_to "已捐赠企业名单",newadmin_companies_path(type: 1),class: "block font20 grey6 pd10 bgreyf #{'border2' if params[:type] == '1'}",style: "border-bottom: none;"
  .border2.pd20{style: "margin-top: -2px;"}
    - if params[:type] == "1"
      - _collection = Kaminari.paginate_array(collection.select{|n| n if n.school_items.count > 0 }).page(params[:page]).per(6)
      - _collection.each do |_item|
        .list1.clearfix
          .titleimg.fl
            = image_tag _item.logo.url,size: "54x54"
          .title.fl.ml20
            %div
              = link_to _item.name,edit_newadmin_company_path(_item),target: "_blank",class: "grey9 font24"
            .mt10
              = link_to _item.site,_item.site,:class => "grey9 font18", :target => "_blank"
          .btns.fr.clearfix
            .fl
              .font24.grey9
                企业类别
              .mt10
                = link_to "学校名单","javascript:;",target: "_blank",class: "btn1 school-item",:"data-school-item" => _item.school_items.map(&:name).join(",")
    - if params[:type] == "0"
      - _collection = Kaminari.paginate_array(collection.select{|n| n if n.school_items.count == 0 }).page(params[:page]).per(6)
      - _collection.each do |_item|
        .list1.clearfix
          .titleimg.fl
            = image_tag _item.logo.url,size: "54x54"
          .title.fl.ml20
            %div
              = link_to _item.name,edit_newadmin_company_path(_item),target: "_blank",class: "grey9 font24"
            .mt10
              = link_to _item.site,_item.site,:class => "grey9 font18", :target => "_blank"
  = paginate _collection

#main-container-info.absolute.clearfix
  #info-left.fl.mt10
    #line1.centerText
      企业数量：
      = Company.count
  #info-right.fl
    = link_to image_tag("newadmin/new-btn.jpg"),new_newadmin_company_path



:coffeescript
  $ ->
    $("body").on "click",".school-item", ->
      str = $(this).attr("data-school-item")
      str2 = ""
      $.each str.split(/,|，/),(index,_obj)->
        str2 += '<div class="fl w200 font18 pd10">'+_obj+'</div>'
      _content = '<div class="clearfix w500 pd20 h400" style="overflow-y: auto;">'+ str2
      _content += '</div>'

      $.fancybox type: "inline", title: "捐赠学校名单", content: _content, width: "480", height: "480", titlePosition: "inside"

    $('.fancybox').fancybox(
      padding : 0,
      autoScale:true,
      width:1000,
      height:600,
      openEffect: 'elastic'
    )

app/views/newadmin/companies/new.html.haml
#main-container-title
  %span
    创建企业
#main-container-body
  = render "shared/flash"

  = simple_form_for resource || Company.new, url: newadmin_companies_path() do |f|
    = render partial: "form", locals: { f: f, ftype: :new  }